#!/usr/bin/env node
/**
 * Generates src/data/hero-glyphs.ts — the SVG data behind the hand-written hero title.
 *
 * The Home hero draws "NTU / DEEPSPEED" stroke by stroke (see src/scripts/home.ts). To do that
 * with a filled display face we need two things per letter: the glyph outline from the font,
 * and a hand-authored "pen path" (the centre line of the marker stroke) that masks the fill in
 * writing order. This script lays the text out with the font's advance widths and kerning,
 * exactly as the CSS text it replaces, and bakes both into a typed module.
 *
 *   yarn hero-glyphs        (downloads Permanent Marker from the Google Fonts repo; Apache-2.0)
 *
 * Re-run it if the title text, the font, or tools/hero-glyphs/pens.json changes. Pen paths are
 * in glyph-local font units (baseline y=0, y down); check coverage against the outlines before
 * committing — a pen that misses part of a letter leaves that part to pop in when the mask lifts.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import opentype from "opentype.js";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const OUT = join(root, "src", "data", "hero-glyphs.ts");
const FONT_URL =
  "https://raw.githubusercontent.com/google/fonts/main/apache/permanentmarker/PermanentMarker-Regular.ttf";
const LINE_HEIGHT = 0.9; // matches .hero-display line-height
// The hero copy. `accentFrom` = index of the first glyph rendered in race red.
const LINES = [
  { text: "NTU" },
  { text: "DEEPSPEED", accentFrom: 4 },
];

async function loadFont() {
  const cache = join(tmpdir(), "ntu-deepspeed-hero-glyphs");
  const file = join(cache, "PermanentMarker-Regular.ttf");
  if (!existsSync(file)) {
    mkdirSync(cache, { recursive: true });
    const res = await fetch(FONT_URL);
    if (!res.ok) throw new Error(`Font download failed: ${res.status} ${FONT_URL}`);
    writeFileSync(file, Buffer.from(await res.arrayBuffer()));
  }
  const buf = readFileSync(file);
  return opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
}

const font = await loadFont();
const upm = font.unitsPerEm;
const { ascender, descender } = font.tables.hhea;
const lineBox = LINE_HEIGHT * upm;
// CSS centres the font's content area (ascent + descent) inside the line box.
const baseline0 = (lineBox - (ascender - descender)) / 2 + ascender;

const pens = JSON.parse(readFileSync(join(here, "pens.json"), "utf8"));
const outlines = {};
const instances = [];
let maxWidth = 0;

LINES.forEach((line, li) => {
  const glyphs = font.stringToGlyphs(line.text);
  const y = baseline0 + li * lineBox;
  let x = 0;
  glyphs.forEach((g, i) => {
    if (i > 0) x += font.getKerningValue(glyphs[i - 1], g);
    const char = line.text[i];
    if (!outlines[char]) outlines[char] = g.getPath(0, 0, upm).toPathData(1);
    if (!pens.paths[char]) throw new Error(`No pen path for "${char}" in pens.json`);
    instances.push({ char, x: Math.round(x), y: Math.round(y), red: i >= (line.accentFrom ?? Infinity) });
    x += g.advanceWidth;
  });
  maxWidth = Math.max(maxWidth, x);
});

const PAD = 24;
const viewBox = [-PAD, 0, Math.round(maxWidth) + 2 * PAD, Math.round(LINES.length * lineBox)];
const penData = Object.fromEntries(
  Object.entries(pens.paths).map(([c, list]) => [
    c,
    list.map((p) => (typeof p === "string" ? { d: p, w: pens.width } : { d: p.d, w: p.w ?? pens.width })),
  ]),
);

const ts = `// GENERATED by tools/hero-glyphs/build.mjs — do not edit by hand. Run \`yarn hero-glyphs\`.
// Permanent Marker (Apache-2.0) outlines + pen paths for the hand-written hero title.

export interface HeroPen {
  /** Centre line of one marker stroke, glyph-local font units (baseline y=0, y down). */
  d: string;
  /** Mask stroke width in font units. */
  w: number;
}

export interface HeroGlyph {
  char: string;
  /** Glyph origin inside the viewBox (font units). */
  x: number;
  y: number;
  /** Rendered in race red instead of the text colour. */
  red: boolean;
}

export const heroGlyphs = {
  font: ${JSON.stringify(font.names.fontFamily?.en ?? "Permanent Marker")},
  unitsPerEm: ${upm},
  viewBox: ${JSON.stringify(viewBox.join(" "))},
  /** Rendered size in em of the surrounding font-size, so it scales exactly like the text did. */
  widthEm: ${(viewBox[2] / upm).toFixed(4)},
  heightEm: ${(viewBox[3] / upm).toFixed(4)},
  /** Glyph outlines by character (glyph-local, baseline y=0). */
  outlines: ${JSON.stringify(outlines, null, 2)} as Record<string, string>,
  /** Pen strokes by character, in writing order. */
  pens: ${JSON.stringify(penData, null, 2)} as Record<string, HeroPen[]>,
  /** Every glyph on the two lines, in writing order. */
  glyphs: ${JSON.stringify(instances, null, 2)} as HeroGlyph[],
};
`;
writeFileSync(OUT, ts);
console.log(
  `hero-glyphs: ${instances.length} glyphs, ${Object.keys(outlines).length} unique, viewBox ${viewBox.join(" ")} → ${OUT}`,
);
